service: ImageLocker
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    name: image-locker-api

functions:
  LockerImagePro:
    handler: index.handler
    events:
      - httpApi:
          path: /lockImage
          method: post
      - httpApi:
          path: /private
          method: get
      - httpApi:
          path: /login
          method: post
      - httpApi:
          path: /register
          method: post
