service: ImageLocker
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: 
          path: /
          method: get
      - httpApi: 
          path: /path
          method: get
      - httpApi:
          path: /private
          method: get
      - httpApi:
          path: /login
          method: post
      - httpApi:
          path: /register
          method: post

