service: ImageLocker
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    name: image-locker-api
    cors: true

functions:
  LockerImagePro:
    handler: index.handler
    events:
      - httpApi: "*"