service: ImageLocker
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    name: image-locker-api

functions:
  lockImage:
    handler: index.handler
    events:
      - httpApi:
          path: /lockImage
          method: ANY

plugins:
  - serverless-offline
