/**
 * Server Side Rendering
 */
import { APIGatewayEvent, APIGatewayProxyResult } from "aws-lambda";
import * as React from "react";
import { renderToString } from "react-dom/server";

import Lock from "../Lock";
import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";

/**
 * Server-side rendering
 */
export default async function render(event: APIGatewayEvent): Promise<APIGatewayProxyResult> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <Lock />
    </ConfigContext.Provider>,
  );

  const renderedHtml = html({ stats, content, config });

  return {
    statusCode: 200,
    headers: {
      "Content-Type": "text/html",
    },
    body: renderedHtml,
  };
}
